variables:
  PROD_URI: 'walletsrv.connectblockchain.net'
  STAGE_URI: 'stage0.walletsrv.connectblockchain.net'
  LOG_LINES: 125  # Bump this number to view more lines in the log with each run.
  # Remember: You can restart the deployment job for that ENV to see a fresh output and not break anything.
  DEPLOY_APP: wallet-server

stages:
  - build
  - deploy

include:
    - project: 'netzilla/ci-templates'
      file: '/bb.yml'

Build App:
  variables:
    ARTIFACTS: lib
  extends:
    - .build_node

Deploy Staging:
  extends:
    - .bb_rsync_staging
  before_script:
    - echo "$JWT_PRIVATE" > jwtrsa-private.key && echo "$JWT_PUBLIC" > jwtrsa-public.pem
    - echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json
    - echo "$DB_CONNECTIONS" > authDbConnections.json
    - echo "$ENV" > .env

Deploy Production:
  extends:
    - .bb_rsync_production
  before_script:
    - echo "$JWT_PRIVATE" > jwtrsa-private.key && echo "$JWT_PUBLIC" > jwtrsa-public.pem
    - echo "$FIREBASE_SERVICE_ACCOUNT" > serviceAccountKey.json
    - echo "$DB_PROD_CONNECTIONS" > authDbConnections.json
    - echo "$ENV_PROD" > .env