variables:
  # CONNECT
  PROD_URI_CONNECT: 'walletsrv.connectblockchain.net'
  STAGE_URI_CONNECT: 'stage0.walletsrv.connectblockchain.net'

  # GREEN
  PROD_URI_GREEN: 'walletsrv.share.green'
  STAGE_URI_GREEN: 'stage0.walletsrv.share.green'

  # CODEX
  PROD_URI_CODEX: 'walletsrv.codexunited.com'
  STAGE_URI_CODEX: 'stage0.walletsrv.codexunited.com'

  # ARACDE
  PROD_URI_ARCADE: 'n0.walletsrv.arcadeblockchain.com'
  STAGE_URI_ARCADE: 'stage0.walletsrv.arcadeblockchain.com'

  # BLUE
  PROD_URI_ARCADE: 'walletsrv.blueunitedhealth.com'
  STAGE_URI_ARCADE: 'stage0.walletsrv.blueunitedhealth.com'

  LOG_LINES: 100 # Bump this number to view more lines in the log with each run.
  # Remember: You can restart the deployment job for that ENV to see a fresh output and not break anything.
  DEPLOY_APP: wallet-server

include:
  - project: 'netzilla/ci-templates'
    file: '/bb.yml'

Build App:
  variables:
    ARTIFACTS: lib
  extends:
    - .build_node

######################################
# STAGING DEPLOYS
######################################

Deploy CONNECT Staging:
  variables:
    DEPLOY_URI: $MASTER_STAGE_URI
    SERVER_HOSTKEYS: $MASTER_STAGE_SERVER_HOSTKEYS
    DEPLOY_APP_REPLACE: wallet-server-connect
    NODE_PORT_REPLACE: 3720
    ENV: $CONNECT_ENV
  extends:
    - .bb_rsync_staging_jwt_firebase

Deploy GREEN Staging:
  variables:
    DEPLOY_URI: $MASTER_STAGE_URI
    SERVER_HOSTKEYS: $MASTER_STAGE_SERVER_HOSTKEYS
    DEPLOY_APP_REPLACE: wallet-server-green
    NODE_PORT_REPLACE: 3721
    ENV: $GREEN_ENV
  extends:
    - .bb_rsync_staging_jwt_firebase

Deploy CODEX Staging:
  variables:
    DEPLOY_URI: $MASTER_STAGE_URI
    SERVER_HOSTKEYS: $MASTER_STAGE_SERVER_HOSTKEYS
    DEPLOY_APP_REPLACE: wallet-server-codex
    NODE_PORT_REPLACE: 3722
    ENV: $CODEX_ENV
  extends:
    - .bb_rsync_staging_jwt_firebase

Deploy ARCADE Staging:
  variables:
    DEPLOY_URI: $MASTER_STAGE_URI
    SERVER_HOSTKEYS: $MASTER_STAGE_SERVER_HOSTKEYS
    DEPLOY_APP_REPLACE: wallet-server-arcade
    NODE_PORT_REPLACE: 3723
    ENV: $ARCADE_ENV
  extends:
    - .bb_rsync_staging_jwt_firebase

Deploy BLUE Staging:
  variables:
    DEPLOY_URI: $MASTER_STAGE_URI
    SERVER_HOSTKEYS: $MASTER_STAGE_SERVER_HOSTKEYS
    DEPLOY_APP_REPLACE: wallet-server-blue
    NODE_PORT_REPLACE: 3724
    ENV: $ARCADE_ENV
  extends:
    - .bb_rsync_staging_jwt_firebase

######################################
# PRODUCTION DEPLOYS
######################################

Deploy CONNECT Production:
  variables:
    DEPLOY_URI: $PROD_URI_CONNECT
    SERVER_HOSTKEYS: $CONNECT_SERVER_HOSTKEYS
    ENV_PROD: $CONNECT_ENV_PROD
  extends:
    - .bb_rsync_production_jwt_firebase

Deploy GREEN Production:
  variables:
    DEPLOY_URI: $PROD_URI_GREEN
    SERVER_HOSTKEYS: $GREEN_SERVER_HOSTKEYS
    ENV_PROD: $GREEN_ENV_PROD
  extends:
    - .bb_rsync_production_jwt_firebase

Deploy CODEX Production:
  variables:
    DEPLOY_URI: $PROD_URI_CODEX
    SERVER_HOSTKEYS: $CODEX_SERVER_HOSTKEYS
    ENV_PROD: $CODEX_ENV_PROD
  extends:
    - .bb_rsync_production_jwt_firebase

Deploy ARCADE Production:
  variables:
    DEPLOY_URI: $PROD_URI_ARCADE
    SERVER_HOSTKEYS: $ARCADE_SERVER_HOSTKEYS
    ENV_PROD: $ARCADE_ENV_PROD
  extends:
    - .bb_rsync_production_jwt_firebase
    
Deploy ARCADE Production:
  variables:
    DEPLOY_URI: $PROD_URI_BLUE
    SERVER_HOSTKEYS: $BLUE_SERVER_HOSTKEYS
    ENV_PROD: $BLUE_ENV_PROD
  extends:
    - .bb_rsync_production_jwt_firebase
