type ReturnToken {
  token: String!
  twoFaEnabled: Boolean!
  twoFaSecret: String
  twoFaQrCode: String
}

type TwoFaRegisterResponse {
  twoFaSecret: String
  twoFaQrCode: String
}

type TwoFaValidationResponse {
  authenticated: Boolean!
  newToken: String
}

type Mutation {
  login(token: String!): ReturnToken!
  twoFaRegister: TwoFaRegisterResponse!
}

type Query {
  twoFaValidate(totpToken: String!): TwoFaValidationResponse!
  isClientSecretRequired: Boolean!
}
