type CartAddress {
  coinSymbol: String
  address: String!
  qrCode: String!
}

type Mutation {
  getCartAddress(
    coinSymbol: String
    orderId: String!
    affiliateId: String
    affiliateSessionId: String
  ): [CartAddress]!
  sendCartTransaction(
    coinSymbol: String!
    orderId: String!
    amount: String!
    walletPassword: String!
    affiliateId: String
    affiliateSessionId: String
  ): TxSendResponse!
}
