type CartAddress {
  coinSymbol: String
  address: String!
  qrCode: String!
}

type CartOrderStatusResponse {
  success: Int!
  message: String!
  status: String
}

type Query {
  getCartOrderStatus(
    orderId: String!
    orderType: String!
    coinSymbol: String!
  ): CartOrderStatusResponse
}

type Mutation {
  getCartAddress(
    coinSymbol: String!
    orderId: String!
    amount: String!
    affiliateId: String
    affiliateSessionId: String
    utmVariables: String
  ): [CartAddress]!
  sendCartTransaction(
    coinSymbol: String!
    orderId: String!
    amount: String!
    walletPassword: String!
    affiliateId: String
    affiliateSessionId: String
    utmVariables: String
  ): TxSendResponse!
}
