type SupportedFavorite {
  name: String!
  symbol: String!
  following: Boolean!
}

type Query {
  favorites: [SupportedFavorite!]!
  supportedFavorites: [SupportedFavorite!]!
}

type Mutation {
  addFavorite(symbol: String!): MutationResponse!
  removeFavorite(symbol: String!): MutationResponse!
}
