type FavoriteFullData {
  changePercent24Hour: Float!
  price: Float!
  symbol: String!
  name: String!
  imageUrl: String!
  supply: Float!
  marketCap: Float!
}

type SupportedFavorite {
  name: String!
  symbol: String!
}

type Query {
  favorites: [FavoriteFullData!]!
  supportedFavorites: [SupportedFavorite!]!
}

type Mutation {
  addFavorite(symbol: String!): [FavoriteFullData!]!
  removeFavorite(symbol: String!): [FavoriteFullData!]!
}
