type DistributionPoint {
  pointType: String!
  amount: Int!
}

type TokenReceived {
  token: String!
  amount: Float!
}

type UserDistributionData {
  firstName: String
  lastName: String
  email: String
  userId: String
  totalPoolPoints: Int
  points: [DistributionPoint!]
  tokensReceived: [TokenReceived!]
}

type Query {
  distributionData(email: String!, date: Date!): UserDistributionData
}
