input BuySellCoinInput {
  buyingCoin: String!
  quantity: Int
  sellingCoin: String!
  price: Float
}
type Conversion {
  buyingCoin: String!
  quantity: Int
  sellingCoin: String!
  price: Float!
  fees: Float
  expires: Date!
}
input CompletedInput {
  from_uuid: String
  limit: Int
}
enum Status {
  CONVERTING
  COMPLETE
}
type OrderStatus {
  orderId: String!
  status: Status!
  bought: Int
  sold: Int
  price: Float
  quantity: Int
}

type OpenOrderItem {
  orderId: String!
  quantity: String!
  name: String!
  description: String!
  image: String!
  price: Float!
  timestamp: Date!
}

input BuyItem {
  itemId: String!
  sellingCoin: String!
  buyingCoin: String!
  quantity: Int
  price: Float
}

input SellItem {
  itemId: String!
  price: Float!
  quantity: Int
  sellingCoin: String!
  buyingCoin: String!
}
type CoinResponse {
  address: String!
  ticker: String!
}

type ConvertQueries {
  status(orderId: String!): Status!
  pricesAndFees(buySellCoin: BuySellCoinInput!): Conversion!
  completed(filter: CompletedInput): [OrderStatus!]
  pending: [OrderStatus!]
  coins: [CoinResponse!]!
}
type ConvertMutations {
  coin(buySellCoin: BuySellCoinInput!, walletPassword: String!): OrderStatus!
  cancel(orderId: String!, walletPassword: String!): OrderStatus!
}
type ItemQueries {
  items(buySellCoin: BuySellCoinInput!): [OpenOrderItem!]
  buyStatus(orderId: String!): OrderStatus!
  sellStatus(orderId: String!): OrderStatus!
}
type ItemMutations {
  buy(buyItem: BuyItem!, walletPassword: String!): OrderStatus!
  sell(sellItem: SellItem!, walletPassword: String!): OrderStatus!
  sellMany(sellItem: [SellItem!]!, walletPassword: String!): [OrderStatus!]!
  cancel(orderId: String!, walletPassword: String!): OrderStatus!
}
type Query {
  convert: ConvertQueries
  item: ItemQueries
}
type Mutation {
  convert: ConvertMutations
  item: ItemMutations
}
