type Friend {
  id: ID!
  displayName: String
  profilePic: String
  active: Boolean!
  canNudge: Boolean!
}

type Query {
  friends: [Friend!]!
}

type Mutation {
  nudgeFriend(id: String!): MutationResponse!
}
