type GameSubItem {
  id: String!
  aquisitionType: String!
  dateAquired: Int!
  gameItemId: String!
  lootBoxId: String
}

type GameItem {
  id: String
  name: String!
  description: String!
  image: String!
  icon: String!
  game: String!
  coin: String!
  tradeWaitTime: Int!
  withdrawalWaitTime: Int!
  galaFee: Float!
  quantityNeeded: Int
  items: [GameSubItem!]
}

type FarmBot {
  id: String
  name: String!
  image: String!
  description: String!
  icon: String!
  game: String!
  coin: String!
  tradeWaitTime: Int!
  withdrawalWaitTime: Int!
  galaFee: Float!
  requiredPieces: [GameItem!]!
}

type Query {
  ownedItems: [GameItem!]!
  farmBotRequired: FarmBot!
}
