type GameSubItem {
  tokenId: String!
  aquisitionType: String!
  dateAquired: Int!
  gameItemId: String!
  lootBoxId: String
  isListed: Boolean!
}

type GameItem {
  nftBaseId: String
  name: String!
  description: String!
  image: String!
  icon: String!
  game: String!
  coin: String!
  tradeWaitTime: Int!
  withdrawalWaitTime: Int!
  galaFee: Float!
  quantityNeeded: Int
  hexcode: String
  label: String!
  rarity: GameItemRarity
  items: [GameSubItem!]
}

type FarmBot {
  id: String
  name: String!
  image: String!
  description: String!
  icon: String!
  game: String!
  coin: String!
  tradeWaitTime: Int!
  withdrawalWaitTime: Int!
  galaFee: Float!
  requiredPieces: [GameItem!]!
}

type GameItemRarity {
  icon: String!
  label: String!
  supplyLimit: Int!
  hexcode: String
}

type GameProduct {
  id: String!
  name: String!
  coin: String!
  game: String!
  nftBaseId: String
  priceUsd: Float!
  basePriceUsd: Float!
  description: String!
  image: String!
  quantities: [Int!]!
  rarity: GameItemRarity
}

type BuyGameProductsResponse {
  items: [GameItem!]!
  transactionHash: String!
  totalBtc: Float!
}

type Query {
  ownedItems: [GameItem!]!
  farmBotRequired: FarmBot!
  gameProducts: [GameProduct!]!
}

type Mutation {
  openLootBoxes(lootBoxIds: [String!]): MutationResponse!
  buyGameProducts(
    quantity: Int!
    productId: String!
    walletPassword: String!
    orderContext: OrderContext
  ): BuyGameProductsResponse!
}
