type PoolInfo {
  poolAddress: String!
  price0: String!
  price1: String!
}

type txResponse {
  message: String!
}

type TokenId {
  message: String
}

input CollectOptions {
  tokenId: Int!
  expectdCurrencyOwed0: Int!
}

type Mutation {
  createPosition(token0: String!, token1: String!, fee: Int!): PoolInfo
  addLiquidity(
    startingPrice: String!
    minPrice: String!
    maxPrice: String!
    amountToken1: String!
    amountToken2: String!
    walletPassword: String!
  ): txResponse
  collectLPTokens(tokenId: Int!): TokenId
}
