type Product {
  id: String!
  name: String!
  shownPrice: Int!
  description: String!
}

type NodesInfo {
  online: Int
  owned: Int
}

type Query {
  productById(id: String!): Product!
  nodesInfo: NodesInfo
}
type Mutation {
  buyNode(
    quantity: Int!
    coinSymbol: String!
    productId: String!
    walletPassword: String!
    orderContext: OrderContext
  ): TxSendResponse!
}
