type UserProfile {
  email: String!
  firstName: String!
  lastName: String!
  displayName: String
  phone: String
  phoneCountry: String
  id: ID!
  created: Date!
  currency: String!
  profilePhotoUrl: String
  language: String
  role: String!
}

input CreateUserInput {
  token: String!
  firstName: String!
  lastName: String!
  displayName: String
  profilePhotoFilename: String
  phone: String
  referredBy: String
  language: String
  referralContext: OrderContext
}

input UpdateUserInput {
  firstName: String
  lastName: String
  displayName: String
  profilePhotoFilename: String
  phone: String
  email: String
  password: String
}

type DisplayNameUniqueResponse {
  unique: Boolean!
  displayName: String!
}

type Query {
  profile: UserProfile!
  displayNameUnique(displayName: String!): DisplayNameUniqueResponse!
}

type Mutation {
  createUser(userInfo: CreateUserInput!): ReturnToken!
  updateUser(userInfo: UpdateUserInput!): MutationResponse!
  unsubscribe(userId: String!, emailList: String!): MutationResponse!
}
