type UserProfile {
  email: String!
  firstName: String!
  lastName: String!
  displayName: String
  phone: String
  phoneCountry: String
  id: ID!
  created: Date!
  currency: String!
  profilePhotoUrl: String
  language: String
  communicationConsent: Boolean
  role: String!
  number: String
  emailVerified: Date
}

input CreateUserInput {
  token: String!
  firstName: String!
  lastName: String!
  displayName: String
  profilePhotoFilename: String
  communicationConsent: Boolean
  phone: String
  referredBy: String
  language: String
  referralContext: OrderContext
}

input UpdateUserInput {
  firstName: String
  lastName: String
  displayName: String
  profilePhotoFilename: String
  communicationConsent: Boolean
  phone: String
  email: String
  password: String
}

input AcceptAgreementsInput {
  privacyPolicy: Boolean
  termsAndConditions: Boolean
  ipAddress: String
}

type DisplayNameUniqueResponse {
  unique: Boolean!
  displayName: String!
}

type NeededAgreementsResponse {
  agreementNames: [String]!
}

type Query {
  profile: UserProfile!
  displayNameUnique(displayName: String!): DisplayNameUniqueResponse!
  neededAgreements: NeededAgreementsResponse!
}

type Mutation {
  createUser(userInfo: CreateUserInput!, ipAddress: String): ReturnToken!
  updateUser(userInfo: UpdateUserInput!): MutationResponse!
  unsubscribe(userId: String!, emailList: String!): MutationResponse!
  acceptAgreements(agreementInfo: AcceptAgreementsInput!): MutationResponse!
  sendVerifyEmail(newAccount: Boolean): MutationResponse!
  verifyEmailAddress(token: String!): MutationResponse!
}
