type UserProfile {
  email: String!
  firstName: String!
  lastName: String!
  displayName: String
  phone: String
  phoneCountry: String
  id: ID!
  created: Date!
  currency: String!
  profilePhotoUrl: String
  language: String
}

input CreateUserInput {
  token: String!
  firstName: String!
  lastName: String!
  displayName: String
  profilePhotoUrl: String
  phone: String
  referredBy: String
  utmInfo: [String!]
  language: String
}

input UpdateUserInput {
  firstName: String
  lastName: String
  displayName: String
  profilePhotoUrl: String
  phone: String
  email: String
  password: String
}

type Query {
  profile: UserProfile!
}

type Mutation {
  createUser(userInfo: CreateUserInput!): ReturnToken!
  updateUser(userInfo: UpdateUserInput!): MutationResponse!
}
