type Vault {
  symbol: String!
  name: String!
  icon: String!
  contractAddress: String!
  balance: Float!
  fees: VaultGasFee!
}

type VaultTransaction {
  userId: String!
  symbol: String!
  tokenId: String
  isNft: Boolean!
  amount: Float!
  created: Date!
  status: String!
  dateMint: Date
  txMint: String
}

type VaultGasFee {
  symbolToMint: String!
  symbolAcceptFee: String!
  amount: Float!
  expires: Date!
  name: String!
}

type VaultRetrieveResponse {
  data: String
  error: String
}

type Mutation {
  vault: [Vault]!
  vaultGas(coinSymbol: String!): VaultGasFee!
  vaultTransactions(coinSymbol: String!, filterType: String): [VaultTransaction]
  vaultRetrieve(coinSymbol: String!, amount: Float!): VaultRetrieveResponse!
}